support random theme selection

diff --git a/.local/bin/selecttheme b/.local/bin/selecttheme
--- a/.local/bin/selecttheme
+++ b/.local/bin/selecttheme
@@ -31,20 +31,35 @@ set_signal_config() {
     sed -i '/theme-setting/c\  "theme-setting": "'$1'",' "$XDG_CONFIG_HOME"/Signal/ephemeral.json
 }
 
-set_configs() {
+set_theme() {
     set_alacritty_config "$1"
     set_nvim_config "$1"
     set_waybar_config "$1"
     set_fuzzel_config "$1"
     set_mako_config "$1" "$2"
     set_signal_config "$2"
+    setwal "$1"
 }
 
-OPTION=$(printf "Everforest\nGruvbox Material\nNord\nRosé Pine\nRosé Pine Dawn" | dmenu-wl -p "  ")
-case "$OPTION" in
-  "Everforest") set_configs everforest dark;;
-  "Gruvbox Material") set_configs gruvbox-material dark;;
-  "Nord") set_configs nord dark;;
-  "Rosé Pine") set_configs rose-pine dark;;
-  "Rosé Pine Dawn") set_configs rose-pine-dawn light;;
-esac
+THEMES="everforest
+gruvbox-material
+nord
+rose-pine
+rose-pine-dawn"
+
+select_theme() {
+    case "$1" in
+      "everforest") set_theme everforest dark;;
+      "gruvbox-material") set_theme gruvbox-material dark;;
+      "nord") set_theme nord dark;;
+      "rose-pine") set_theme rose-pine dark;;
+      "rose-pine-dawn") set_theme rose-pine-dawn light;;
+      "random") set_theme "$(printf "$THEMES" | shuf -n 1)" dark;;
+      *) printf "Error: Invalid theme.\n"; exit 1;;
+    esac
+}
+
+[ -n "$1" ] && select_theme "$1" && exit
+
+OPTION=$(printf "$THEMES" | dmenu-wl -p "  ")
+select_theme "$OPTION"
